**Ranking de Filmes e Séries: Scraping e Visualização**

Ana Paula Gomes de Azevedo - BI Master 2019.2

*Para executar o código é necessário ter o arquivo Chromedriver (Chrome) ou Geckodriver (Mozilla Firefox) na mesma pasta*

https://chromedriver.chromium.org/downloads ou https://github.com/mozilla/geckodriver/releases

In [1]:
import pandas as pd
from selenium import webdriver
import time

In [2]:
#driver = webdriver.Chrome()
driver = webdriver.Firefox()

**Parte 1 - Scraping dos 100 melhores filmes e séries de TV segundo a Empire**

In [3]:
def scrap_empire():
    
    l_pos, l_img, l_title, l_date, l_review = [],[],[],[],[]

    # Para cada série da lista, guardar: título, data, review e endereço da imagem

    for num in range(0,100):
        img = driver.find_element_by_xpath("//div[@data-test='listicle-item-"+str(num)+"']//img").get_attribute("data-src")

        title = driver.find_element_by_xpath("//div[@data-test='listicle-item-"+str(num)+"']//h3").text
        i = title.find(')')
        if i==-1: i=-2
        title = title[i+2:]

        try:
            date = driver.find_element_by_xpath("//div[@data-test='listicle-item-"+str(num)+"']//strong").text
            if not date[:4].isdigit(): date='$'
        except:
            date='$'

        review = driver.find_element_by_xpath("//div[@data-test='listicle-item-"+str(num)+"']//p").text
        review = review.replace(date,'').replace("\n","")

        l_pos.append(100-num)
        l_img.append(img)
        l_title.append(title)
        l_date.append(date)
        l_review.append(review)
        
    dict_empire = {'#':l_pos,'Title':l_title,'Date':l_date,'Review':l_review,'Image':l_img}
        
    return dict_empire

Filmes

In [4]:
%%time
url = r'https://www.empireonline.com/movies/features/best-movies-2/'
driver.get(url)
df_empire_movies = pd.DataFrame(scrap_empire())
df_empire_movies

Wall time: 33.2 s

,#,Title,Date,Review,Image
0,100,Stand By Me,1986,Rob Reiner's adaptation of Stephen King's nove...,//cdn.onebauer.media/one/media/5e62/24d4/08ba/...
1,99,Raging Bull,1980,Martin Scorsese and Robert De Niro have togeth...,//cdn.onebauer.media/one/media/5d2d/d990/853e/...
2,98,Amelie,2001,Jean-Pierre Jeunet's beautifully whimsical Par...,//cdn.onebauer.media/one/empire-images/feature...
3,97,Titanic,1997,James Cameron doesn't do things by halves. His...,//cdn.onebauer.media/one/lifestyle-images/cele...
4,96,Good Will Hunting,1997,Remember when young actor buddies Matt Damon a...,//cdn.onebauer.media/one/media/5e62/2a32/2cd5/...
...,...,...,...,...,...
95,5,Pulp Fiction,1994,If Reservoir Dogs was a blood-spattered callin...,//cdn.onebauer.media/one/media/5d54/32ec/9619/...
96,4,The Shawshank Redemption,1994,"The warm, leathery embrace of Morgan Freeman's...",//cdn.onebauer.media/one/empire-images/feature...
97,3,The Dark Knight,2008,Easily as influential on the genre as that oth...,//cdn.onebauer.media/one/lifestyle-legacy/80/e...
98,2,The Empire Strikes Back,$,"The original ""this one's darker"" sequel, and b...",//cdn.onebauer.media/one/lifestyle-legacy/6d/7...
99,1,The Godfather,$,Stanley Kubrick once described Francis Ford Co...,//cdn.onebauer.media/one/empire-images/feature...

In [5]:
df_empire_movies.to_excel('empire_list_movies.xlsx')

Séries de TV

In [6]:
%%time
url = r'https://www.empireonline.com/tv/features/best-tv-shows-ever-2/'
driver.get(url)
df_empire_tv = pd.DataFrame(scrap_empire())
df_empire_tv

Wall time: 19 s

,#,Title,Date,Review,Image
0,100,Rome,2005-2007,Before Game Of Thrones came along to conquer t...,//cdn.onebauer.media/one/media/5da5/8ce8/9389/...
1,99,Farscape,1999-2003,Empire's Editor-In-Chief Terri White might ins...,//cdn.onebauer.media/one/media/5da5/8d10/9389/...
2,98,Big Little Lies,2017-present,Big Little Lies was always going to be somethi...,//cdn.onebauer.media/one/media/5da5/8d42/9389/...
3,97,Broadchurch,2013-2017,Before he became Doctor Who's latest showrunne...,//cdn.onebauer.media/one/media/5da5/8d5d/9389/...
4,96,Life On Mars,2006-2007,A high concept police series that never let it...,//cdn.onebauer.media/one/media/5da5/8db9/9389/...
...,...,...,...,...,...
95,5,Friends,1994-2004,How is it that a certain digital TV channel ca...,//cdn.onebauer.media/one/media/5da5/9d91/9389/...
96,4,The Wire,$,David Simon famously once said that he intende...,//cdn.onebauer.media/one/media/5da5/9dbe/9389/...
97,3,The Sopranos,$,Those who tuned into the first episode of The ...,//cdn.onebauer.media/one/media/5da5/9dcf/9389/...
98,2,Game Of Thrones,2011-2019,TV – and the lesser restrictions/bigger budget...,//cdn.onebauer.media/one/media/5da5/9df1/9389/...
99,1,Breaking Bad,$,"""It doesn't get really good until Season 2,"" p...",//cdn.onebauer.media/one/media/5da5/9e04/9389/...

In [7]:
df_empire_tv.to_excel('empire_list_tv.xlsx')

**Parte 2 - Scraping no IMDB**

In [8]:
url = r'https://www.imdb.com/'
driver.get(url)

In [9]:
# Correção de alguns títulos
d_titles_tv = {'The Bridge':'Bron','Star Trek':'Star Trek Original', 'The Office (UK)':'The Office (2001)','Oz':'Oz (1997)', 'Angel':'Angel (1999)'}
d_titles_movies = {'Rocky':'Rocky (1976)','Predator':'Predator (1987)','Fargo':'Fargo (1996)'}

In [10]:
def scrap_imdb (df_empire, tipo):
    l_title, l_grade, l_synopsis, l_awards, l_creator, l_actors, l_date, l_seasons, l_pop, l_length, l_budget, l_gross = [], [], [], [], [], [], [], [], [], [], [], []

    # Para cada série da lista da Empire, buscar o título no IMDB e salvar as informações

    for i in df_empire.index:

        title = df_empire.loc[i,'Title']
        
        try: 
            # Verifica se é preciso corrigir o título
            if tipo == 'tv':
                title = d_titles_tv[title]
            else: #movie
                title = d_titles_movies[title]
        except:
            pass
        
        try:
            # Busca o título e seleciona primeira opção
            driver.find_element_by_xpath("//input[@id='suggestion-search']").send_keys(title)
            driver.find_element_by_xpath("//button[@id='suggestion-search-button']").click()
            driver.find_element_by_xpath("//tr[@class='findResult odd'][1]/td[2]/a").click()

            # Grava as informações de interesse

            grade = driver.find_element_by_xpath("//span[contains(@class,'AggregateRatingButton__RatingScore')]").text

            popularity = driver.find_element_by_xpath("//div[contains(@class,'AggregateRatingButton__TotalRatingAmount')]").text
            if popularity[-1] == 'K':
                popularity = int(float(popularity[:-1])*1000)
            elif popularity[-1] == 'M':
                popularity = int(float(popularity[:-1])*1000000)

            synopsis = driver.find_element_by_xpath("//span[@data-testid='plot-l']").text
            if synopsis == '': synopsis = driver.find_element_by_xpath("//span[@data-testid='plot-xl']").text

            try:
                creator = driver.find_element_by_xpath("//li[@data-testid='title-pc-principal-credit'][1]/div/ul/li/a").text
            except:
                creator = ''

            try:
                awards = driver.find_element_by_xpath("//li[@data-testid='award_information']/a").text
                if awards == 'Awards': awards = driver.find_element_by_xpath("//li[@data-testid='award_information']/div/ul/li/span").text
            except:
                awards = ''
            
            c = '3' 
            if tipo == 'tv': c = '2' 
            actors = ''
            n = 1
            while n <= 3:
                try:
                    actors += ', ' + driver.find_element_by_xpath("//li[@data-testid='title-pc-principal-credit']["+c+"]/div/ul/li["+str(n)+"]/a").text
                    n += 1
                except:
                    break
            actors = actors[2:]

            if tipo == 'tv':
                date = driver.find_element_by_xpath("//ul[@data-testid='hero-title-block__metadata']/li[2]/a").text
                try:
                    seasons = driver.find_element_by_xpath("//select[@id='browse-episodes-season']/option[2]").text
                except:
                    seasons = '1'
                
                l_seasons.append(seasons)
                
            else: #movie
                date = driver.find_element_by_xpath("//ul[@data-testid='hero-title-block__metadata']/li[1]/a").text
                
                length = driver.find_element_by_xpath("//ul[@data-testid='hero-title-block__metadata']/li[3]").text
                
                budget = driver.find_element_by_xpath("//li[@data-testid='title-boxoffice-budget']/div/ul/li/span").text
                budget = budget.replace(',','').replace('$','').replace(' (estimated)','')
                try:
                    test = int(budget[:1])
                except: #se não for dólar, manter vazio
                    budget = ''
                    
                gross = driver.find_element_by_xpath("//li[@data-testid='title-boxoffice-cumulativeworldwidegross']/div/ul/li/span").text
                gross = gross.replace(',','').replace('$','').replace(' (estimated)','')
                
                l_length.append(length)
                l_budget.append(budget)
                l_gross.append(gross)

            l_title.append(df_empire.loc[i,'Title'])
            l_grade.append(grade)
            l_synopsis.append(synopsis)
            l_awards.append(awards)
            l_creator.append(creator)
            l_actors.append(actors)
            l_date.append(date)
            l_pop.append(popularity)
            
        except:
            print('Erro: '+ title)
        
    if tipo == 'tv': 
        dict_imdb = {'Title':l_title,'Date':l_date,'Grade':l_grade,'Grade_Count':l_pop,'Synopsis':l_synopsis,'Seasons':l_seasons,'Awards':l_awards,'Creator':l_creator,'Actors':l_actors}
    else: #movie
        dict_imdb = {'Title':l_title,'Date':l_date,'Grade':l_grade,'Grade_Count':l_pop,'Length':l_length,'Synopsis':l_synopsis,'Awards':l_awards,'Director':l_creator,'Actors':l_actors, 'Budget':l_budget,'Gross':l_gross}

    return dict_imdb

Filmes

In [11]:
%%time
df_imdb_movies = pd.DataFrame(scrap_imdb(df_empire_movies,"movie"))
df_imdb_movies

Wall time: 10min 40s

,Title,Date,Grade,Grade_Count,Length,Synopsis,Awards,Director,Actors,Budget,Gross
0,Stand By Me,1986,8.1,373000,1h 29min,"After the death of one of his friends, a write...",Nominated for 1 Oscar,Rob Reiner,"Wil Wheaton, River Phoenix, Corey Feldman",8000000,52287414
1,Raging Bull,1980,8.2,329000,2h 9min,"The life of boxer Jake LaMotta, whose violence...",Won 2 Oscars,Martin Scorsese,"Robert De Niro, Cathy Moriarty, Joe Pesci",18000000,23402427
2,Amelie,2001,8.3,717000,2h 2min,Amélie is an innocent and naive girl in Paris ...,Nominated for 5 Oscars,Jean-Pierre Jeunet,"Audrey Tautou, Mathieu Kassovitz, Rufus",10000000,173959536
3,Titanic,1997,7.8,1100000,3h 14min,A seventeen-year-old aristocrat falls in love ...,Won 11 Oscars,James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",200000000,2201647264
4,Good Will Hunting,1997,8.3,886000,2h 6min,"Will Hunting, a janitor at M.I.T., has a gift ...",Won 2 Oscars,Gus Van Sant,"Robin Williams, Matt Damon, Ben Affleck",10000000,225933435
...,...,...,...,...,...,...,...,...,...,...,...
95,Pulp Fiction,1994,8.9,1900000,2h 34min,"The lives of two mob hitmen, a boxer, a gangst...",Won 1 Oscar,Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Jackson",8000000,213928762
96,The Shawshank Redemption,1994,9.3,2400000,2h 22min,Two imprisoned men bond over a number of years...,Nominated for 7 Oscars,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton",25000000,28817291
97,The Dark Knight,2008,9.0,2400000,2h 32min,When the menace known as the Joker wreaks havo...,Won 2 Oscars,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart",185000000,1005973645
98,The Empire Strikes Back,1980,8.7,1200000,2h 4min,After the Rebels are brutally overpowered by t...,Won 2 Oscars,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher",18000000,538375067
99,The Godfather,1972,9.2,1700000,2h 55min,An organized crime dynasty's aging patriarch t...,Won 3 Oscars,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan",6000000,246120986

In [13]:
df_imdb_movies.to_excel('imdb_list_movies.xlsx')

Séries de TV

In [14]:
%%time
df_imdb_tv = pd.DataFrame(scrap_imdb(df_empire_tv,"tv"))
df_imdb_tv

Wall time: 10min 44s

,Title,Date,Grade,Grade_Count,Synopsis,Seasons,Awards,Creator,Actors
0,Rome,2005–2007,8.7,159000,A down-to-earth account of the lives of both i...,2,Won 7 Primetime Emmys,Bruno Heller,"Kevin McKidd, Ray Stevenson, Polly Walker"
1,Farscape,1999–2003,8.3,34000,"Thrown into a distant part of the universe, an...",4,Nominated for 1 Primetime Emmy,Rockne S. O'Bannon,"Ben Browder, Claudia Black, Anthony Simcoe"
2,Big Little Lies,2017–2019,8.5,167000,The apparently perfect lives of upper-class mo...,2,Won 8 Primetime Emmys,David E. Kelley,"Reese Witherspoon, Nicole Kidman, Shailene Woo..."
3,Broadchurch,2013–2017,8.4,100000,The murder of a young boy in a small coastal t...,3,26 wins & 29 nominations total,Chris Chibnall,"David Tennant, Olivia Colman, Jodie Whittaker"
4,Life On Mars,2006–2007,8.3,29000,After being involved in a car accident in 2006...,2,9 wins & 30 nominations total,Matthew Graham,"John Simm, Philip Glenister, Liz White"
...,...,...,...,...,...,...,...,...,...
95,Friends,1994–2004,8.9,872000,Follows the personal and professional lives of...,10,Won 6 Primetime Emmys,David Crane,"Jennifer Aniston, Courteney Cox, Lisa Kudrow"
96,The Wire,2002–2008,9.3,296000,"The Baltimore drug scene, as seen through the ...",5,Nominated for 2 Primetime Emmys,David Simon,"Dominic West, Lance Reddick, Sonja Sohn"
97,The Sopranos,1999–2007,9.2,318000,New Jersey mob boss Tony Soprano deals with pe...,6,Won 21 Primetime Emmys,David Chase,"James Gandolfini, Lorraine Bracco, Edie Falco"
98,Game Of Thrones,2011–2019,9.2,1800000,Nine noble families fight for control over the...,8,Won 59 Primetime Emmys,David Benioff,"Emilia Clarke, Peter Dinklage, Kit Harington"
99,Breaking Bad,2008–2013,9.4,1500000,A high school chemistry teacher diagnosed with...,5,Won 16 Primetime Emmys,Vince Gilligan,"Bryan Cranston, Aaron Paul, Anna Gunn"

In [15]:
df_imdb_tv.to_excel('imdb_list_tv.xlsx')

Script executado com sucesso em 12/07/2021 às 15:00

É possível que ao longo do tempo os sites alterem a estrutura HTML e algum erro aconteça

**Parte 3 - Visualização dos rankings e análise de dados**

*Verificar arquivo do PowerBI Visualizacao_Filmes_Series.pbix*